[workspace]
resolver = "2"
members = [
  "utils"
  ,"core"
  ,"message-derive"
  ,"remote"
  ,"cluster"
]

[workspace.dependencies]
static_assertions = "1.1.0"
tracing = "0.1"
async-trait = "0.1.80"
once_cell = "1.19.0"
thiserror = "1.0.61"
num_enum = "0.7.2"
futures = "0.3.30"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dashmap = "6.0.0-rc.1"

tokio = { version = "1.37.0" , features = ["full"] }

prost = "0.13.0"
prost-types = "0.13"
tonic = "0.12.3"
tonic-types = "0.12.3"
