[package]
name = "nexus-rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
prost = "0.12.6"
prost-types = "0.12"
async-trait = "0.1.80"
futures = "0.3.30"
tokio = { version = "1.37.0" , features = ["full"] }
tokio-condvar = "0.3.0"
thiserror = "1.0.61"
anyhow = "1.0.45"
oni-comb-uri-rs = "0.2.1"
log = "0.4.21"
rand = "0.9.0-alpha.1"
base64-string-rs = "0.0.1"
time = "0.3.36"
backtrace = "0.3"
once_cell = "1.19.0"
num_enum = "0.7.2"
dashmap = "6.0.0-rc.1"
siphasher = "1.0.1"
uuid = { version = "1.9.0", features = ["v4"] }
env_logger = "0.11.3"
static_assertions = "1.1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
mockall = "0.12.1"
[build-dependencies]
prost-build = { version = "0.12.6" }
