[package]
name = "nexus-acto-message-derive-rs"
version = "0.8.4"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.36"
quote = "1.0.36"
syn = {version = "2.0.74", features = ["full", "extra-traits", "visit-mut", "visit"]}